### ISSUE TITLE
Symfony\Component\Mailer\Exception\IncompleteDsnException: User is not set. when attempting to send mail with Postmark

### ISSUE THREAD

**Issue by josephcrowell** [wintercms/wn-driverpostmark-plugin#1]
Using latest postmark driver and latest version of Winter CMS

Here's a stack trace.

```
Symfony\Component\Mailer\Exception\IncompleteDsnException: User is not set. in /home/comput80/public_html/vendor/symfony/mailer/Transport/AbstractTransportFactory.php:44
Stack trace:
#0 /home/comput80/public_html/vendor/symfony/postmark-mailer/Transport/PostmarkTransportFactory.php(28): Symfony\Component\Mailer\Transport\AbstractTransportFactory->getUser()
#1 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(339): Symfony\Component\Mailer\Bridge\Postmark\Transport\PostmarkTransportFactory->create()
#2 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(164): Illuminate\Mail\MailManager->createPostmarkTransport()
#3 /home/comput80/public_html/vendor/winter/storm/src/Mail/MailManager.php(53): Illuminate\Mail\MailManager->createSymfonyTransport()
#4 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(97): Winter\Storm\Mail\MailManager->resolve()
#5 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(75): Illuminate\Mail\MailManager->get()
#6 /home/comput80/public_html/vendor/winter/storm/src/Mail/MailManager.php(27): Illuminate\Mail\MailManager->mailer()
#7 /home/comput80/public_html/vendor/winter/storm/src/Mail/MailServiceProvider.php(19): Winter\Storm\Mail\MailManager->mailer()
#8 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(885): Winter\Storm\Mail\MailServiceProvider->Winter\Storm\Mail\{closure}()
#9 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\Container\Container->build()
#10 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\Container\Container->resolve()
#11 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\Foundation\Application->resolve()
#12 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\Container\Container->make()
#13 /home/comput80/public_html/vendor/winter/storm/src/Foundation/Application.php(323): Illuminate\Foundation\Application->make()
#14 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1431): Winter\Storm\Foundation\Application->make()
#15 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(222): Illuminate\Container\Container->offsetGet()
#16 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(193): Illuminate\Support\Facades\Facade::resolveFacadeInstance()
#17 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(332): Illuminate\Support\Facades\Facade::getFacadeRoot()
#18 /home/comput80/public_html/plugins/josephcrowell/magicforms/classes/mails/Notification.php(61): Illuminate\Support\Facades\Facade::__callStatic()
#19 /home/comput80/public_html/plugins/josephcrowell/magicforms/classes/traits/SendMails.php(40): JosephCrowell\MagicForms\Classes\Mails\Notification->send()
#20 /home/comput80/public_html/plugins/josephcrowell/magicforms/classes/traits/SendMails.php(20): JosephCrowell\MagicForms\Classes\MagicForm->sendNotification()
#21 /home/comput80/public_html/plugins/josephcrowell/magicforms/classes/MagicForm.php(149): JosephCrowell\MagicForms\Classes\MagicForm->sendEmails()
#22 /home/comput80/public_html/modules/cms/classes/ComponentBase.php(194): JosephCrowell\MagicForms\Classes\MagicForm->onFormSubmit()
#23 /home/comput80/public_html/modules/cms/classes/Controller.php(839): Cms\Classes\ComponentBase->runAjaxHandler()
#24 /home/comput80/public_html/modules/cms/classes/Controller.php(730): Cms\Classes\Controller->runAjaxHandler()
#25 /home/comput80/public_html/modules/cms/classes/Controller.php(387): Cms\Classes\Controller->execAjaxHandlers()
#26 /home/comput80/public_html/modules/cms/classes/Controller.php(220): Cms\Classes\Controller->runPage()
#27 /home/comput80/public_html/modules/cms/classes/CmsController.php(41): Cms\Classes\Controller->run()
#28 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Cms\Classes\CmsController->run()
#29 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#30 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch()
#31 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#32 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Routing\Route->run()
#33 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#34 /home/comput80/public_html/plugins/winter/translate/classes/LocaleMiddleware.php(31): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Winter\Translate\Classes\LocaleMiddleware->handle()
#36 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#38 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#40 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#42 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle()
#43 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#45 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#47 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\Pipeline\Pipeline->then()
#49 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\Routing\Router->runRouteWithinStack()
#50 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\Routing\Router->runRoute()
#51 /home/comput80/public_html/vendor/winter/storm/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute()
#52 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Winter\Storm\Router\CoreRouter->dispatch()
#53 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#54 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 /home/comput80/public_html/vendor/winter/storm/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(25): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#56 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Winter\Storm\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#57 /home/comput80/public_html/vendor/winter/storm/src/Foundation/Http/Middleware/CheckForTrustedProxies.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#58 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Winter\Storm\Foundation\Http\Middleware\CheckForTrustedProxies->handle()
#59 /home/comput80/public_html/vendor/winter/storm/src/Http/Middleware/TrustHosts.php(46): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#60 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Winter\Storm\Http\Middleware\TrustHosts->handle()
#61 /home/comput80/public_html/plugins/winter/redirect/classes/RedirectMiddleware.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#62 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Winter\Redirect\Classes\RedirectMiddleware->handle()
#63 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#64 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline->then()
#65 /home/comput80/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#66 /home/comput80/public_html/index.php(42): Illuminate\Foundation\Http\Kernel->handle()
#67 {main}
```

**Comment by mjauvin** [comment]
@josephcrowell can you try what I commited in latest dev-main ?

**Comment by mjauvin** [comment]
Fixed by https://github.com/wintercms/wn-driverpostmark-plugin/commit/a8da6c3d56ef9c4e37c5e9fbee7d3b3107077544

**Comment by josephcrowell** [comment]
> @josephcrowell can you try what I commited in latest dev-main ?

That worked, thanks!
